spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_test_container
    username: root
    password: root
